context('Testkunde bearbeiten', () => {
    it('Testkunden bearbeiten und Daten kontrollieren',()=>{
        cy.visit('https://localhost:4200/kunden/suche')
        cy.get('#usernameInput').type('admin')
        cy.get('#passwordInput').type('p')
        cy.get('#navbarCollapse').contains('Login').click()
        cy.get('#navbarCollapse').contains('Logout')
        cy.contains('Suchen').click()
        cy.contains('Testkunde').click()
        cy.contains('Bearbeiten').click()
        cy.contains('Divers').click()
        cy.contains('Männlich').click()
        cy.contains('Stammdaten aktualisieren').click()
        cy.visit('https://localhost:4200/kunden/suche')
        cy.contains('Suchen').click()
        cy.contains('Testkunde').click()
        cy.contains('Männlich')
    })
})